spring:
  datasource:
    url: spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/backenddatabase
    username: seth2
    password: secretPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
